### ISSUE TITLE
juan - Announced orders of a position are not deleted when liquidation happens

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-12-flatmoney-judging#287]
juan

high

# Announced orders of a position are not deleted when liquidation happens

## Summary
Announced orders of a position are not deleted when liquidation happens

## Vulnerability Detail
When a position is liquidated, an existing announced order for that position is not deleted. This means that the user's order can still be executed after liquidation of the position. This is only an issue for leverageAdjut orders, and only if the points module is removed (and this has been said to be a temporary feature by the devs, so the points module is likely to be removed in the future).

## Impact
Once the points module is removed, a user's leverageAdjust order with positive `additionalSizeAdjustment` will still execute after the position has been liquidated.

## Code Snippet
https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/LeverageModule.sol#L147

## Tool used
Manual Review

## Recommendation
Delete announced orders of a position when the position is liquidated

**Comment by santipu03** [comment]
Escalate

This issue should be invalid because the transaction will revert when checking the owner of the ERC-721 position. If the position has been liquidated, the leverage adjustment is going to revert in [this line](https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/LeverageModule.sol#L226). Because the token has been burned, `ownerOf` will revert.

The Watson here is making assumptions on future code changes but the attack path is not feasible with the current state of the code.

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This issue should be invalid because the transaction will revert when checking the owner of the ERC-721 position. If the position has been liquidated, the leverage adjustment is going to revert in [this line](https://github.com/sherlock-audit/2023-12-flatmoney/blob/main/flatcoin-v1/src/LeverageModule.sol#L226). Because the token has been burned, `ownerOf` will revert.
> 
> The Watson here is making assumptions on future code changes but the attack path is not feasible with the current state of the code. 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by RealLTDingZhen** [comment]
Escalate

Should be invalid because this has the same path as [issue227](https://github.com/sherlock-audit/2023-12-flatmoney-judging/issues/227)

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> Should be invalid because this has the same path as [issue227](https://github.com/sherlock-audit/2023-12-flatmoney-judging/issues/227)

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0xjuaan** [comment]
I submitted this issue because:
1. When I told the sponsor about it, they thanked me and said that they would definitely need to fix it.
2. The sponsor also said that they are likely to remove the PointsModule in the future, and that would cause the vulnerability.

I do understand if this were to be invalidated since the attack is technically blocked. 

However if I did not provide this information to the protocol, they could have easily removed the points module features, deployed the vulnerable code to mainnet, and user funds would be lost. But this report has prevented that, so I believe that it should be rewarded.

**Comment by nevillehuang** [comment]
@0xjuaan Can you provide a coded PoC and a clearer description of what is the impact here, namely (fund loss, DoS or breaks core contract functionality)

**Comment by 0xjuaan** [comment]
@nevillehuang A coded PoC won't work, since the issue requires the 3 lines of points module code to be removed. 

However if it was removed as stated by sponsor, here's the impact (fund loss for users):
User announces order to increase position size -> Position gets liquidated -> Keeper executes user's  pending order (since it wasn't deleted) -> User can never get back those funds since any attempt to announce an order for that position will revert.

Do you still want a coded PoC? It would require removing the points modules code from the LeverageModule contract

**Comment by nevillehuang** [comment]
Which 3 lines are you referring to? Are they code logic that are intended to be removed?

@0xjuaan If yes please do that, I believe if the understanding of the codebase is correct, its can warrant validity based on this comment [here](https://github.com/sherlock-audit/2023-12-jojo-exchange-update-judging/issues/30#issuecomment-1936076314)

**Comment by 0xjuaan** [comment]
The 3 lines are [here](https://github.com/sherlock-audit/2023-12-flatmoney/blob/bba4f077a64f43fbd565f8983388d0e985cb85db/flatcoin-v1/src/LeverageModule.sol#L226-L229) and yes, the sponsor has said that the points module is likely to be removed, and they encouraged me to submit this issue + admitted that they would make sure to fix it. You can confirm this with @rashtrakoff

I already had most of the PoC ready, since I sent it to the sponsor on discord a while ago. However sponsor only let me know at the end of the contest that the points module is likely to be removed, so I only had 8 mins to submit this report at the end of the contest, which is why the explanation is a bit limited in the report and PoC wasn't provided.

PoC is below. To run it, place the given function in `Liquidate.t.sol` and comment out the three lines of code that I linked above.
<details>
<summary> POC </summary>

```javascript
function test_executeLeverageAdjust_postLiquidation() public {
    setWethPrice(1000e8);

    uint256 tokenId = announceAndExecuteDepositAndLeverageOpen({
        traderAccount: alice,
        keeperAccount: keeper,
        depositAmount: 100e18,
        margin: 10e18,
        additionalSize: 30e18,
        oraclePrice: 1000e8,
        keeperFeeAmount: 0
    });
    
    setWethPrice(750e8);

    // user announces order, this sends 3e18 of margin to DelayedOrder
    announceAdjustLeverage(alice, tokenId, 3e18, 2e18 , 0);

    skip(uint256(vaultProxy.minExecutabilityAge())); 

    // user gets liquidated, before the 3e18 of margin goes to vault
    vm.startPrank(liquidator);
    liquidationModProxy.liquidate(tokenId);

    // only now after liquidation, the 3e18 of margin is sent to the vault
    executeAdjustLeverage(keeper, alice, 750e8);
    vm.stopPrank();

    // Try to close position, but can't (so funds are lost forever)
    vm.prank(alice);
    vm.expectRevert("ERC721: invalid token ID");
    delayedOrderProxy.announceLeverageClose(tokenId, 500, 1e18);
}
```
</details>

Thank you for looking into this @nevillehuang

**Comment by RealLTDingZhen** [comment]
> The sponsor also said that they are likely to remove the PointsModule in the future, and that would cause the vulnerability.

Where did sponsors say that?

**Comment by rashtrakoff** [comment]
@0xjuaan I didn't say it is likely to be removed but rather it is not a core fixture of the protocol so points per dize can be set to 0 or in other words _can_ be deprecated.

**Comment by 0xjuaan** [comment]
![image](https://github.com/sherlock-audit/2023-12-flatmoney-judging/assets/122077337/5c458bf8-66c1-437c-879c-0fb03a318af1)

> not a permanent fixture

This is what I was going off of, I thought this means that the points module is not permanent.

**Comment by rashtrakoff** [comment]
Yes, that's what I wanted to say. Someday we will deprecate it. Which day, not sure.

**Comment by securitygrid** [comment]
Can deleting code be considered an issue? unacceptable

**Comment by nevillehuang** [comment]
Based on sponsors comments [here](https://github.com/sherlock-audit/2023-12-flatmoney-judging/issues/287#issuecomment-1961283663), I believe this issue to be invalid.

**Comment by Czar102** [comment]
Planning to invalidate as to my knowledge, there should be no expectation for the codebase to work without the `PointsModule`. Will accept only the first escalation.

**Comment by Czar102** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [santipu03](https://github.com/sherlock-audit/2023-12-flatmoney-judging/issues/287/#issuecomment-1955081905): accepted
- [RealLTDingZhen](https://github.com/sherlock-audit/2023-12-flatmoney-judging/issues/287/#issuecomment-1956653337): rejected

**Comment by sherlock-admin4** [comment]
The protocol team fixed this issue in PR/commit https://github.com/dhedge/flatcoin-v1/pull/295.
